name: "Coverity Commit Checker"
description: "Will check that is the commit needed or not and if it is, it will do it"
author: Jouni Lehto
branding:
  icon: code
  color: blue
inputs:
  project:
    description: Coverity Connect project name. If not given, then using project from environment variables as a default
    required: false
    default: ${{github.env.project}}
  stream:
    description: Coverity Connect project stream name. If not given, then using stream from environment variables as a default
    required: false
    default: ${{github.env.project}}
  cov_username:
    description: Coverity Connect username
    required: true
  cov_password:
    description: Coverity Connect password
    required: true
  cov_url:
    description: URL for Coverity Connect where the analysis tar file can be downloaded
    required: true
  cov_install_folder:
    description: Place where coverity commands are found. Ex. /coverity/bin/. Not required if Coverity tools are in PATH.
    required: false
  intermediate_dir:
    description: Itermediate directory
    required: true
  log_level:
    description: Logging level
    default: DEBUG
    required: false
  teams_webhook_url:
    description: Microsoft Teams WebHook URL. By giving this, the Teams notification is activated
    required: false
  force_commit:
    description: Setting this true, it will do the commit and will not do any checkings.
    default: "false"
    required: false
  dryrun:
    description: Set this true, if you want to run tests and not to do the commit.
    default: "false"
    required: false
  break_build:
    description: Set this true, if you want to break the build, if there are new findings.
    default: "false"
    required: false
  emit_threshold:
    description: With this you can set the emit threshold, the default is 95
    default: '95'
    required: false
  viewID:
    description: ID of that view which result is used to get findings
    required: false

runs:
  using: composite
  steps:
    # First step is to install needed Python modules
    - run: |
        pip3 install requests pymsteams
      shell: bash
    # Second step is to run the Python script
    - run: |
        python3 ${{github.action_path}}/commitChecker.py --viewID=${{inputs.viewID}} --emit_threshold=${{inputs.emit_threshold}} --break_build=${{inputs.break_build}} --dryrun=${{inputs.dryrun}} --force_commit=${{inputs.force_commit}} --teams_webhook_url="${{inputs.teams_webhook_url}}" --coverity_home="${{inputs.cov_install_folder}}" --coverity_url=${{inputs.cov_url}} --project_name=${{inputs.project}} --username=${{inputs.cov_username}} --password=${{inputs.cov_password}} --stream_name=${{inputs.stream}} --intermediate_dir=${{inputs.intermediate_dir}} --log_level=${{inputs.log_level}}
      shell: bash
